// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func EmailField() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div><label for=\"email\" class=\"block text-sm font-medium text-zinc-700\">Email</label> <input id=\"email\" name=\"email\" type=\"text\" data-bind:email class=\"mt-1 block w-full rounded-lg border border-zinc-300 px-4 py-2.5 text-sm outline-none transition-colors\" data-attr:class=\"`\r\n\t\t\t\tmt-1 block w-full rounded-lg border px-4 py-2.5 text-sm outline-none transition-colors\r\n\t\t\t\t${$submitted\r\n\t\t\t\t\t? (validationController.isValidEmail($email) ? 'border-green-500' : 'border-red-500')\r\n\t\t\t\t\t: 'border-zinc-300'\r\n\t\t\t\t}\r\n\t\t\t`\"><div class=\"hidden mt-1 text-sm text-red-500\" data-attr:class=\"\r\n\t\t\t\t$submitted && !validationController.isValidEmail($email)\r\n\t\t\t\t\t? 'mt-1 text-sm text-red-500'\r\n\t\t\t\t\t: 'hidden'\r\n\t\t\t\"><span data-attr:class=\"\r\n\t\t\t\t\t$email == ''\r\n\t\t\t\t\t\t? 'inline'\r\n\t\t\t\t\t\t: 'hidden'\r\n\t\t\t\t\">Email is required</span> <span data-attr:class=\"\r\n\t\t\t\t\t$email != '' && !validationController.isValidEmail($email)\r\n\t\t\t\t\t\t? 'inline'\r\n\t\t\t\t\t\t: 'hidden'\r\n\t\t\t\t\">Enter a valid email</span></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
